"""Add nutrition_date column

Revision ID: 268e193d0a8a
Revises: cdcdc2eb7f86
Create Date: 2023-12-02 11:09:30.943641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268e193d0a8a'
down_revision = 'cdcdc2eb7f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('nutrition_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition', 'nutrition_date')
    # ### end Alembic commands ###
