"""empty message

Revision ID: cdcdc2eb7f86
Revises: 7e93963878bb
Create Date: 2023-12-02 11:07:24.340059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcdc2eb7f86'
down_revision = '7e93963878bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition', sa.Column('nutrition_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition', 'nutrition_date')
    # ### end Alembic commands ###
